# This workflow will build and push a Node.js application to an Azure Web App 
# when a commit is pushed to your default branch.

# Workflow assumes the Azure Web App is already created.
# Follow the instructions to set up Azure and GitHub Actions:
# https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
# https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: atelier-devops-2024    # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist'       # Set this to your build output folder
  NODE_VERSION: '20.x'                      # Set this to the Node.js version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build --if-present

    - name: Clean up unnecessary files
      run: |
        rm -rf node_modules
        rm -rf tests
        mkdir -p dist
        # Adjust commands to copy only necessary files into the dist folder
        cp -R public src package.json package-lock.json dist/

    - name: Archive files for deployment
      run: zip -r node-app.zip ./dist

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: node-app.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: Extract artifact
      run: unzip node-app.zip

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
